### ISSUE TITLE
Kicked from lobby

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/java-ice-adapter#10]
When testing on my laptop I sometimes get kicked from my own lobb.y

**Comment by Geosearchef** [comment]
-> To reproduce:

Host a game, connect on a different client and abort.

**Comment by Geosearchef** [comment]
Happens when both clients are in the same network.

**Comment by muellni** [comment]
is this an ICE issue? Are you alone in the lobby? My guess is that it is impossible for the lobby host to reconnect during lobby

**Comment by muellni** [comment]
And you'll get kicked once you connect with the same credentials in another client instance.

**Comment by Geosearchef** [comment]
It happens the moment anyone connects. I get thrown out of my own lobby the moment someone connects using the py client. This is a py client/server issue.
