### ISSUE TITLE
Increase lobby connection wait time before proxy is engaged.

### ISSUE THREAD

**Issue by robbotik** [FAForever/java-ice-adapter#16]
It seems the proxy between players is engaged too quickly in game lobbies. People who would otherwise be able to connect normally end up routed through the proxy instead. In this case, it's possible to avoid the proxy by having people join in different orders. It's assumed this is due to an individuals hardware or network location able to accept connections slightly quicker than it's able to instigate them.

This is mostly an issue in regions far outside the proxy server location, where being connected that way is unstable and causes extreme, unplayable lag in games.

**Comment by Geosearchef** [comment]
This has nothing to do with the adapter and is due to the connectivity establishment protocol thereofer requiring a change in the ice library used here.

About high latency in that case, what would really be needed is an additional relay server.
