### ISSUE TITLE
Relicensing request to MIT to all authors

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/java-ice-adapter#37]
According to the Git history the majority of code was developed under GPL v3
It seems to got accidentially delete with commit d8d44e3788467dfba855416deafc885446a4a935.

In the future we might want to integrate the ice adapter as a library, but this would clash with the java clients MIT license.
Thus I'm asking for permission for all authors to re-license their contributions under the [MIT license](https://opensource.org/licenses/MIT).

Please just respond with a one line like "I approve relicensing my code to MIT".

Current status:

- [x] @Geosearchef 
- [x] @IDragonfire 
- [x] @muellni 
- [x] @reweeden
- [X] @Brutus5000 
- [x] @b2ag 
- [x] @micheljung 
- [x] @Sheikah45

**Comment by Brutus5000** [comment]
I approve relicensing my code to MIT

**Comment by b2ag** [comment]
I approve relicensing my code to MIT.

**Comment by Geosearchef** [comment]
I approve relicensing my code to MIT. Farewall my baby. 🙂

**Comment by muellni** [comment]
I approve relicensing my code to MIT.

**Comment by reweeden** [comment]
I approve relicensing my code to MIT

**Comment by micheljung** [comment]
I approve relicensing my code to MIT

**Comment by 1-alex98** [comment]
It seems that @IDragonfire does not own any code that still lives in master today

**Comment by IDragonfire** [comment]
I approve relicensing my code to MIT
