### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by mankinskin** [FAForever/java-ice-adapter#54]
Occasionally the ICE adapter takes extreme CPU resources. Last game with 12 players first I lost connection to a few players, then reconnected but my whole system was blocked by the ICE adapter. It was just during a regular game.

**Comment by Sheikah45** [comment]
This should be fixed with 3.3.7

**Comment by mankinskin** [comment]
> This should be fixed with 3.3.7

What was the problem?

**Comment by Sheikah45** [comment]
There was a log statement that could get triggered and consume all the CPU cycles writing to the log

**Comment by Brutus5000** [comment]
This log statement was there for 6 years and now it suddenly causes problems. I think it's and indicator to a bigger problem (packets length changed somehow), but it's impossible to see.

**Comment by mankinskin** [comment]
Maybe the log writes should be limited in general? The ICE adapter is crucial for performance, so maybe limiting the resources assigned to non-functional tasks should be kept below a threshold to keep it functional. The logs could just mention that there were too many messages to actually log them, which should already indicate a problem, but at least the adapter may still be able to run normally.

Something like a log buffer only writing to the file every few millis max?

**Comment by Sheikah45** [comment]
Yes but the new alpha client also uses it
