### ISSUE TITLE
Python server disconnects from other peers in lobby

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/java-ice-adapter#8]

**Comment by Geosearchef** [comment]
It can get pretty annoying to time out from a lobby every few minutes cause you lost connection to the server for a split second, there isn't even a reconnect needed here, but the server kicks you out.

**Comment by muellni** [comment]
There's a connectivity checker in the client which will reconnect you once it did not received an answer from the server for 3 seconds.
Maybe we should enable this checker only for launched games.
